version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
      - redis

  web:
    image: nginx:latest
    container_name: laravel-web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    entrypoint: ["/bin/sh", "-c", "php artisan horizon"]
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - redis
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-scheduler
    entrypoint: ["/bin/sh", "-c", "php artisan schedule:work"]
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
