services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - laravel-storage:/var/www/html/storage
    networks:
      - laravel
    depends_on:
      - db
      - redis

  web:
    image: nginx:latest
    container_name: laravel-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - laravel-storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432" # Expose PostgreSQL on host port 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    networks:
      - laravel

  horizon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-horizon
    entrypoint: ["/bin/sh", "-c", "php artisan horizon"]
    volumes:
      - ./:/var/www/html:cached
      - laravel-storage:/var/www/html/storage
    depends_on:
      - app
      - redis
    networks:
      - laravel

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-scheduler
    entrypoint: ["/bin/sh", "-c", "php artisan schedule:work"]
    volumes:
      - ./:/var/www/html:cached
      - laravel-storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - laravel

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue
    working_dir: /var/www/html
    command: php artisan queue:work --tries=3
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
      - laravel-storage:/var/www/html/storage
    depends_on:
      - app
      - redis
    networks:
      - laravel

volumes:
  pgdata:
  laravel-storage:

networks:
  laravel:
    driver: bridge
